version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /examples/vite
    schedule:
      interval: weekly
    groups:
      example-dependencies:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
